abstract class AppStates {}
class InitialState extends AppStates{}
class ChangeBottomNavBarState extends AppStates{}
class CreateDatabase extends AppStates{}
class InsertToDatabase extends AppStates{}
class GetDataFromDatabase extends AppStates{}
class ChangeBottomSheetState extends AppStates{}
class UpdateDatabase extends AppStates{}
class DeleteFromDatabase extends AppStates{}